# 05. Statements

### 空语句

```c++
; // null statement
```

### switch 内部的变量定义

如果程序跳转到了某个特定的 case，则 switch 结构中该 case 标签之前的部分会被忽略掉。这种忽略掉一部分代码的行为引出了一个有趣的问题：如果被略过的代码中含有变量的定义该怎么办？

答案是：如果在某处一个带有初值的变量位于作用域之外，在另一处该变量位于作用域之内，则从前一处跳转到后一处的行为是非法行为。

```c++
case true:
	// 因为程序的执行流程可能绕开下面的初始化语句，所以该 switch 语句不合法
	string file_name;//错误：控制流绕过一个隐式初始化的变量
	int ival = 0; //错误：控制流绕过一个显式初始化的变量
	int jval;//正确：因为 jval 没有初始化
	break;
case false:
	// 正确：jval 虽然在作用域内，但是它没有被初始化
	jval = next_num();// 正确：给 jval 赋一个值
	if (file_name.empty()) // file_name 在作用域内，但是没有被初始化
		//...
```

假设上述代码合法，则一旦控制流直接跳到 false 分支，也就同时略过了变量 file_name 和 ival 的初始化过程。此时这两个变量位于作用域之内，跟在 false 之后的代码试图在尚未初始化的情况下使用它们，这显然是行不通的。因此 C++ 语言规定，不允许跨过变量的初始化语句直接跳转到该变量作用域内的另一个位置。
如果需要为某个 case 分支定义并初始化一个变量，我们应该把变量定义在块内，从而确保后面的所有 case 标签都在变量的作用域之外。

```c++
case true:
{
	//正确：声明语句位于语句块内部
	string file_name = get_file_name();
	// ...
	break;
}
case false:
	if (file_name.empty()) // 错误： file_name 不在作用域之内
```

## try 语句和异常处理

异常处理机制为程序中异常检测和异常处理这两部分的协作提供支持。在 C++ 中，异常处理包括：

- throw 表达式（throw expression），异常检测部分使用 throw 表达式来表示它遇到了无法处理的问题。我们说 throw 引发（raise）了异常。
- try 语句块（try block），异常处理部分使用 try 语句块处理异常。try 语句块以关键字 try 开始，并以一个或多个 catch 子句（catch clause）结束。try 语句块中代码抛出的异常通常会被某个 catch 子句处理。因为 catch 子句“处理”异常，所以它们也被称作异常处理代码（exception handler）。
- 一套异常类（exception class），用于在 throw 表达式和相关的 catch 子句之间传递异常的具体信息。

### throw表达式

程序的异常检测部分使用 throw 表达式引发一个异常。 throw 表达式包含关键字 throw 和紧随其后的一个表达式，其中表达式的类型就是抛出的异常类型。 throw 表达式后面通常紧跟一个分号，从而构成一条表达式语句。

```c++
//首先检查两条数据是否是关于同一种书籍的
if （iteml.isbn() != item2.isbn()）
	throw runtime_error("Data must refer to same ISBN");
//如果程序执行到了这里，表示两个ISBN是相同的
cout << iteml + item2 << endl;
```

在这段代码中，如果 ISBN 不一样就抛出一个异常，该异常是类型 runtime_error 的对象。抛出异常将终止当前的函数，并把控制权转移给能处理该异常的代码。

类型 runtime_error 是标准库异常类型的一种，定义在 stdexcept 头文件中。我们必须初始化 runtime_error 的对象，方式是给它提供一个 string 对象或者一个 C 风格的字符串，这个字符串中有一些关于异常的辅助信息。

###  try语句块

try语句块的通用语法形式是

```c++
try {
	program-statements
} catch（exception-declaration） {
	handler-statements
} catch（exception-declaration） {
	handler-statements
}//...
```

try 语句块的一开始是关键字 try，随后紧跟着一个块，这个块就像大多数时候那样是花括号括起来的语句序列。

跟在 try 块之后的是一个或多个 catch 子句。catch 子句包括三部分：关键字 catch、括号内一个（可能未命名的）对象的声明（称作异常声明，exception declaration）
以及一个块。当选中了某个 catch 子句处理异常之后，执行与之对应的块。catch 一旦完成，程序跳转到 try 语句块最后一个 catch 子句之后的那条语句继续执行。

try 语句块中的 program-statements 组成程序的正常逻辑，像其他任何块一样，program-statements 可以有包括声明在内的任意 C++ 语句。一如往常，try 语句块内声明的变量在块外部无法访问，特别是在 catch 子句内也无法访问。

```c++
while (cin >> iteml >> item2) {
	try {
		//执行添加两个 Sales_item 对象的代码
		//如果添加失败，代码抛出一个 runtime_error 异常
	} catch (runtime_error err) {
		//提醒用户两个ISBN必须一致，询问是否重新输入
		cout << err.what()
		     << "\nTry Again？Enter y or n" << endl;
		charc;
		cin >> c;

		if (! cin || c == 'n')
			break；//跳出while循环
		}
}
```


程序本来要执行的任务出现在 try 语句块中，这是因为这段代码可能会抛出一个 runtime_error 类型的异常。

try 语句块对应一个 catch 子句，该子句负责处理类型为 runtime_error 的异常。如果 try  语句块的代码抛出了 runtime_error 异常，接下来执行 catch 块内的语句。在我们书写的 catch 子句中，输出一段提示信息要求用户指定程序是否继续。如果用户输入 'n'，执行 break 语句并退出 while 循环；否则，直接执行 while 循环的右侧花括号，意味着程序控制权跳回到 while 条件部分准备下一次迭代。

给用户的提示信息中输出了 err.what() 的返回值。我们知道 err 的类型是 runtime_error，因此能推断 what 是 runtime_error 类的一个成员函数。每个标准库异常类都定义了名为 what 的成员函数，这些函数没有参数，返回值是 C 风格字符串（即const char* ）。其中，runtime_error 的 what 成员返回的是初始化一个具体对象时所用的 string 对象的副本。如果上一节编写的代码抛出异常，则本节的 catch 子句输出

```c++
Data must refer to same ISBN
Try Again?Enter y or n
```

### 标准异常

C++ 标准库定义了一组类，用于报告标准库函数遇到的问题。这些异常类也可以在用户编写的程序中使用，它们分别定义在 4 个头文件中：

  exception 头文件定义了最通用的异常类 exception。它只报告异常的发生，不提供任何额外信息。
  stdexcept 头文件定义了几种常用的异常类，详细信息在下表中列出。
  new 头文件定义了 bad_alloc 异常类型，这种类型将在 12.1.2 节详细介绍。
  type_info 头文件定义了 bad_cast 异常类型，这种类型将在 19.2 节详细介绍。

```c++
exception	最常见的问题
runtime_error	只有在运行时才能检测出的问题
range_error	运行时错误：生成的结果超出了有意义的值域范围
overflow_error	运行时错误：计算上溢
underflow_error	运行时错误：计算下溢
logic_error	程序逻辑错误
domain_error	逻辑错误：参数对应的结果值不存在
invalid_argument	逻辑错误：无效参数
length_error	逻辑错误：试图创建一个超出该类型最大长度的对象
out_of_range	逻辑错误：使用一个超出有效范围的值
```


标准库异常类只定义了几种运算，包括创建或拷贝异常类型的对象，以及为异常类型的对象赋值。

我们只能以默认初始化（参见2.2.1节，第40页）的方式初始化 exception、bad_alloc 和 bad_cast 对象，不允许为这些对象提供初始值。

其他异常类型的行为则恰好相反：应该使用 string 对象或者 C 风格字符串初始化这些类型的对象，但是不允许使用默认初始化的方式。当创建此类对象时，必须提供初始值，该初始值含有错误相关的信息。

异常类型只定义了一个名为 what 的成员函数，该函数没有任何参数，返回值是一个指向 C 风格字符串的const char* 。该字符串的目的是提供关于异常的一些文本信息。

what 函数返回的 C 风格字符串的内容与异常对象的类型有关。如果异常类型有一个字符串初始值，则 what 返回该字符串。对于其他无初始值的异常类型来说，what 返回的内容由编译器决定。